### ISSUE TITLE
package.json in nested directory not showing up

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [madskristensen/NpmTaskRunner#57] opened 2018-01-29 14:45 UTC
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.4.81

### Description
When the package.json file is not in the root of a project its tasks are not shown in the Task Runner Explorer. When the same package.json file is moved to the root of the project its in, the tasks do show up.

### Steps to recreate
1. Create a .csproj in visual studio
2. Create a directory (for example: wwwroot) in the project
3. Place a package.json file with npm scripts inside the folder made at 2.

### Current behavior
No tasks are shown.

### Expected behavior
The task should be shown.

**Comment by scottaddie** [comment] 2018-01-29 16:35
Duplicate of https://github.com/madskristensen/NpmTaskRunner/issues/37. This is a known limitation of Task Runner Explorer and cannot be fixed by the extension.

**Closed by scottaddie** 2018-01-29 16:35 UTC
